/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creadorgimnasiaestatica;

/**
 *
 * @author medinillag
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    
    public double ponderacion_transicion;
    public double ponderacion_elemento;
    public double ponderacion_nivel;
    public double racion;
    public int elemento_anterior;
    /*
    0 = no hay elemento anterior
    1 = arabe
    2 = flick
    3 = whip
    4 = mortal
    5 = giro
    6 = 2giro
    */
    public String gimnasia_estatica = "";
    public String numerador = "";
    public String denominador = "";
    
    public Window() {
        initComponents();
        racion = (double)1/26;
        elemento_anterior = 0;
        System.out.println(String.valueOf(racion));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label23 = new java.awt.Label();
        textField19 = new java.awt.TextField();
        label24 = new java.awt.Label();
        textField20 = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        label25 = new java.awt.Label();
        textField21 = new java.awt.TextField();
        checkbox1 = new java.awt.Checkbox();
        button7 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label23.setText("Numerador");

        label24.setText("Denominador");

        button1.setLabel("FLICK");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("WHIP");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setLabel("MORTAL");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setLabel("GIRO");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setLabel("2GIRO");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setLabel("REINICIAR");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        label25.setText("Gimnasia Estatica");

        checkbox1.setLabel("80%");

        button7.setLabel("ARABE");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 432, Short.MAX_VALUE))
                            .addComponent(textField19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField20, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                            .addComponent(textField21, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                        .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(button7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        //FLICK
        ponderacionTransicion(2);
        ponderacion_elemento = 10.0;
        ponderacion_nivel = 40.0;
        if (gimnasia_estatica.equals(""))
        {
            gimnasia_estatica = "FLICK";
        }
        else
        {
            gimnasia_estatica += " FLICK"; 
        }
        textField21.setText(gimnasia_estatica);
        elemento_anterior = 2;
        
        calcularNumerador();
        calcularDenominador();
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        //WHIP
        ponderacionTransicion(3);
        ponderacion_elemento = 25.0;
        ponderacion_nivel = 40.0;
        if (gimnasia_estatica.equals(""))
        {
            gimnasia_estatica = "WHIP";
        }
        else
        {
            gimnasia_estatica += " WHIP"; 
        }
        textField21.setText(gimnasia_estatica);
        elemento_anterior = 3;
        
        calcularNumerador();
        calcularDenominador();
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        //MORTAL
        ponderacionTransicion(4);
        ponderacion_elemento = 50.0;
        ponderacion_nivel = 60.0;
        String t = "MORTAL(60%)";
        if (checkbox1.getState())
        {
            ponderacion_nivel = 80.0;
            t = "MORTAL(80%)";
        }
        if (gimnasia_estatica.equals(""))
        {
            gimnasia_estatica = t;
        }
        else
        {
            gimnasia_estatica += " " + t; 
        }
        textField21.setText(gimnasia_estatica);
        elemento_anterior = 4;
        
        calcularNumerador();
        calcularDenominador();
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        //GIRO
        ponderacionTransicion(5);
        ponderacion_elemento = 80.0;
        ponderacion_nivel = 100.0;
        if (gimnasia_estatica.equals(""))
        {
            gimnasia_estatica = "GIRO";
        }
        else
        {
            gimnasia_estatica += " GIRO"; 
        }
        textField21.setText(gimnasia_estatica);
        elemento_anterior = 5;
        
        calcularNumerador();
        calcularDenominador();
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        //2GIRO
        ponderacionTransicion(6);
        ponderacion_elemento = 100.0;
        ponderacion_nivel = 100.0;
        if (gimnasia_estatica.equals(""))
        {
            gimnasia_estatica = "2GIRO";
        }
        else
        {
            gimnasia_estatica += " 2GIRO"; 
        }
        textField21.setText(gimnasia_estatica);
        elemento_anterior = 6;
        
        calcularNumerador();
        calcularDenominador();
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        textField19.setText("");
        textField20.setText("");
        textField21.setText("");
        
        checkbox1.setState(false);
        
        elemento_anterior = 0;
        
        numerador = "";
        denominador = "";
        gimnasia_estatica = "";
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        //ARABE
        ponderacionTransicion(1);
        ponderacion_elemento = 5.0;
        ponderacion_nivel = 40.0;
        if (gimnasia_estatica.equals(""))
        {
            gimnasia_estatica = "ARABE";
        }
        else
        {
            gimnasia_estatica += " ARABE"; 
        }
        textField21.setText(gimnasia_estatica);
        elemento_anterior = 1;
        
        calcularNumerador();
        calcularDenominador();
    }//GEN-LAST:event_button7ActionPerformed

    public void calcularNumerador()
    {
        if (numerador.equals(""))
        {
            numerador = ponderacion_elemento + "*" + ponderacion_nivel;
        }
        else
        {
            numerador += "+" + ponderacion_elemento + "*(" + ponderacion_nivel + "+" + ponderacion_transicion+ ")";
        }
        textField19.setText(numerador);
    }
    
    public void calcularDenominador()
    {
        if (denominador.equals(""))
        {
            denominador = String.valueOf(ponderacion_elemento);
        }
        else
        {
            denominador += "+" + String.valueOf(ponderacion_elemento);
        }
        textField20.setText(denominador);
    }
    
    public void ponderacionTransicion(int elemento_actual)
    {
        switch (elemento_anterior)
        {
            case 0://no hay elemento anterior
                ponderacion_transicion = racion*0;
                break;
            case 1://ARABE
                switch (elemento_actual)
                {
                    case 1://ARABE
                        ponderacion_transicion = racion*1;
                        break;
                    case 2://FLICK
                        ponderacion_transicion = racion*2;
                        break;
                    case 3://WHIP
                        ponderacion_transicion = racion*5;
                        break;
                    case 4://MORTAL
                        ponderacion_transicion = racion*6;
                        break;
                    case 5://GIRO
                        ponderacion_transicion = racion*17;
                        break;
                }
                break;
            case 2://FLICK
                switch (elemento_actual)
                {
                    case 2://FLICK
                        ponderacion_transicion = racion*3;
                        break;
                    case 3://WHIP
                        ponderacion_transicion = racion*4;
                        break;
                    case 4://MORTAL
                        ponderacion_transicion = racion*11;
                        break;
                    case 5://GIRO
                        ponderacion_transicion = racion*14;
                        break;
                    case 6://2GIRO
                        ponderacion_transicion = racion*22;
                        break;
                }
                break;
            case 3://WHIP
                switch (elemento_actual)
                {
                    case 2://FLICK
                        ponderacion_transicion = racion*9;
                        break;
                    case 3://WHIP
                        ponderacion_transicion = racion*10;
                        break;
                    case 4://MORTAL
                        ponderacion_transicion = racion*12;
                        break;
                    case 5://GIRO
                        ponderacion_transicion = racion*15;
                        break;
                    case 6://2GIRO
                        ponderacion_transicion = racion*23;
                        break;
                }
                break;
            case 4://MORTAL
                switch (elemento_actual)
                {
                    case 2://FLICK
                        ponderacion_transicion = racion*7;
                        break;
                    case 3://WHIP
                        ponderacion_transicion = racion*8;
                        break;
                    case 4://MORTAL
                        ponderacion_transicion = racion*13;
                        break;
                    case 5://GIRO
                        ponderacion_transicion = racion*16;
                        break;
                }
                break;
            case 5://GIRO
                switch (elemento_actual)
                {
                    case 2://FLICK
                        ponderacion_transicion = racion*18;
                        break;
                    case 3://WHIP
                        ponderacion_transicion = racion*19;
                        break;
                    case 4://MORTAL
                        ponderacion_transicion = racion*20;
                        break;
                    case 5://GIRO
                        ponderacion_transicion = racion*21;
                        break;
                }
                break;
            case 6://2GIRO
                switch (elemento_actual)
                {
                    case 2://FLICK
                        ponderacion_transicion = racion*24;
                        break;
                    case 3://WHIP
                        ponderacion_transicion = racion*25;
                        break;
                    case 4://MORTAL
                        ponderacion_transicion = racion*26;
                        break;
                }
                break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Checkbox checkbox1;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.TextField textField19;
    private java.awt.TextField textField20;
    private java.awt.TextField textField21;
    // End of variables declaration//GEN-END:variables
}
