/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gimansiaestatica;

/**
 *
 * @author medinillag
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    
    public boolean flag;
    
    public int valor_arabe;
    public int valor_flick;
    public int valor_backTuck;
    public int valor_whip;
    public int valor_layout;
    public int valor_twist;
    public int valor_2twist;
    
    public int peso_arabe;
    public int peso_flick;
    public int peso_backTuck;
    public int peso_whip;
    public int peso_layout;
    public int peso_twist;
    public int peso_2twist;
    
    public int valor_elemento;
    public int peso_elemento;
    public double transicion;
    public double racion;
    public int elemento_anterior;
    /*
    0 = no hay elemento anterior
    1 = arabe
    2 = flick
    3 = mortal
    4 = whip
    5 = layout
    6 = giro
    7 = 2giro
    */
    
    public int MAX1;
    public int MAX2;
    public int MAX3;
    
    public double r1;
    public double r2;
    public double r3;
    
    public double d1;
    public double d2;
    public double d3;
    
    public String texto_d1;
    public String texto_d2;
    public String texto_d3;
    
    public double DT;
    public double D1;
    public double D2;
    public double D3;
    
    public String texto_D1;
    public String texto_D2;
    public String texto_D3;
    
    public String gimnasia_estatica;
    public String texto_sum_vw1;
    public String texto_sum_trans1;
    public String texto_sum_vw2;
    public String texto_sum_trans2;
    public String texto_sum_vw3;
    public String texto_sum_trans3;
    
    public double sum_vw1;
    public double sum_trans1;
    public double sum_vw2;
    public double sum_trans2;
    public double sum_vw3;
    public double sum_trans3;
    
    public Window() {
        initComponents();
        
        flag = true;
        
        elemento_anterior = 0;
        
        texto_d1 = "";
        texto_d2 = "";
        texto_d3 = "";
        
        texto_D1 = "";
        texto_D2 = "";
        texto_D3 = "";
        
        D1 = 0;
        D2 = 0;
        D3 = 0;
        
        gimnasia_estatica = "";
        texto_sum_vw1 = "";
        texto_sum_trans1 = "";
        texto_sum_vw2 = "";
        texto_sum_trans2 = "";
        texto_sum_vw3 = "";
        texto_sum_trans3 = "";
        
        racion = 3.85;
        
        valor_arabe = 5;
        valor_flick = 10;
        valor_backTuck = 25;
        valor_whip = 35;
        valor_layout = 50;
        valor_twist = 80;
        valor_2twist = 100;
        
        peso_arabe = 20;
        peso_flick = 40;
        peso_backTuck = 60;
        peso_whip = 60;
        peso_layout = 60;
        peso_twist = 80;
        peso_2twist = 100;
        
        r1 = 553.55;
        r2 = 1412.39;
        r3 = 2618.59;
        
        MAX1 = 10;
        MAX2 = 30;
        MAX3 = 60;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("ARABE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("FLICK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("MORTAL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("WHIP");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("LAYOUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("GIRO");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("2GIRO");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("REINICIAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setText("Gimnasia Estatica");

        jLabel2.setText("d1");

        jLabel3.setText("d2");

        jLabel4.setText("d3");

        jLabel5.setText("D1");

        jLabel6.setText("D2");

        jLabel7.setText("D3");

        jLabel8.setText("DT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8))
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8)
                            .addComponent(jTextField9)
                            .addComponent(jTextField11)
                            .addComponent(jTextField10)
                            .addComponent(jTextField13)
                            .addComponent(jTextField12)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(0, 258, Short.MAX_VALUE))))
                    .addComponent(jTextField15)
                    .addComponent(jTextField14)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //FLICK
        Transicion(2);
        valor_elemento = valor_flick;
        peso_elemento = peso_flick;
        if (gimnasia_estatica.equals(""))
        {
            gimnasia_estatica = "FLICK";
        }
        else
        {
            gimnasia_estatica += " FLICK";
        }
        jTextField1.setText(gimnasia_estatica);
        
        calcular_d1();
        calcular_D1();
        calcular_DT();
        elemento_anterior = 2;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //LAYOUT
        Transicion(5);
        valor_elemento = valor_layout;
        peso_elemento = peso_layout;
        if (gimnasia_estatica.equals(""))
        {
            gimnasia_estatica = "LAYOUT";
        }
        else
        {
            gimnasia_estatica += " LAYOUT";
        }
        jTextField1.setText(gimnasia_estatica);
        
        if (elemento_anterior < 3 && elemento_anterior > 0)
        {
            flag = false;
            calcular_d1();
            calcular_D1();
        }
        flag = true;
        calcular_d2();
        calcular_D2();
        calcular_DT();
        elemento_anterior = 5;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //ARABE
        Transicion(1);
        valor_elemento = valor_arabe;
        peso_elemento = peso_arabe;
        if (gimnasia_estatica.equals(""))
        {
            gimnasia_estatica = "ARABE";
        }
        else
        {
            gimnasia_estatica += " ARABE";
        }
        jTextField1.setText(gimnasia_estatica);
        
        calcular_d1();
        calcular_D1();
        calcular_DT();
        elemento_anterior = 1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //MORTAL
        Transicion(3);
        valor_elemento = valor_backTuck;
        peso_elemento = peso_backTuck;
        if (gimnasia_estatica.equals(""))
        {
            gimnasia_estatica = "MORTAL";
        }
        else
        {
            gimnasia_estatica += " MORTAL";
        }
        jTextField1.setText(gimnasia_estatica);
        
        if (elemento_anterior < 3 && elemento_anterior > 0)
        {
            flag = false;
            calcular_d1();
            calcular_D1();
        }
        flag = true;
        calcular_d2();
        calcular_D2();
        calcular_DT();
        elemento_anterior = 3;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //WHIP
        Transicion(4);
        valor_elemento = valor_whip;
        peso_elemento = peso_whip;
        if (gimnasia_estatica.equals(""))
        {
            gimnasia_estatica = "WHIP";
        }
        else
        {
            gimnasia_estatica += " WHIP";
        }
        jTextField1.setText(gimnasia_estatica);
        
        if (elemento_anterior < 3 && elemento_anterior > 0)
        {
            flag = false;
            calcular_d1();
            calcular_D1();
        }
        flag = true;
        calcular_d2();
        calcular_D2();
        calcular_DT();
        elemento_anterior = 4;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //GIRO
        Transicion(6);
        valor_elemento = valor_twist;
        peso_elemento = peso_twist;
        if (gimnasia_estatica.equals(""))
        {
            gimnasia_estatica = "GIRO";
        }
        else
        {
            gimnasia_estatica += " GIRO";
        }
        jTextField1.setText(gimnasia_estatica);
        
        if (elemento_anterior < 3 && elemento_anterior > 0)
        {
            flag = false;
            calcular_d1();
            calcular_D1();
        }
        else if (elemento_anterior < 6 && elemento_anterior > 0)
        {
            flag = false;
            calcular_d2();
            calcular_D2();
        }
        flag = true;
        calcular_d3();
        calcular_D3();
        calcular_DT();
        elemento_anterior = 6;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //2GIRO
        Transicion(7);
        valor_elemento = valor_2twist;
        peso_elemento = peso_2twist;
        if (gimnasia_estatica.equals(""))
        {
            gimnasia_estatica = "2GIRO";
        }
        else
        {
            gimnasia_estatica += " 2GIRO";
        }
        jTextField1.setText(gimnasia_estatica);
        
        if (elemento_anterior < 3 && elemento_anterior > 0)
        {
            flag = false;
            calcular_d1();
            calcular_D1();
        }
        else if (elemento_anterior < 6 && elemento_anterior > 0)
        {
            flag = false;
            calcular_d2();
            calcular_D2();
        }
        flag = true;
        calcular_d3();
        calcular_D3();
        calcular_DT();
        elemento_anterior = 7;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //BOTON REINICIAR
        
        flag = true;
        
        elemento_anterior = 0;
        
        texto_d1 = "";
        texto_d2 = "";
        texto_d3 = "";
        
        texto_D1 = "";
        texto_D2 = "";
        texto_D3 = "";
        
        D1 = 0;
        D2 = 0;
        D3 = 0;
        
        gimnasia_estatica = "";
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    public void calcular_d1()
    {
        if (texto_d1.equals(""))
        {
            if (flag)
            {
                sum_vw1 = valor_elemento*peso_elemento;
                texto_sum_vw1 = String.valueOf(valor_elemento) + "*" + String.valueOf(peso_elemento);
            }
            
            sum_trans1 = transicion;
            texto_sum_trans1 = String.valueOf(transicion);
        }
        else
        {
            if (flag)
            {
                sum_vw1 += valor_elemento*peso_elemento;
                texto_sum_vw1 += " + " + String.valueOf(valor_elemento) + "*" + String.valueOf(peso_elemento);
            }
            
            sum_trans1 += transicion;
            texto_sum_trans1 += " + " + String.valueOf(transicion);
        }
        d1 = sum_vw1 + sum_trans1;
        jTextField2.setText(String.valueOf(d1));
        
        texto_d1 = "(" + texto_sum_vw1 + ") + (" + texto_sum_trans1 + ")"; 
        jTextField3.setText(texto_d1);
    }
    
    public void calcular_d2()
    {
        if (texto_d2.equals(""))
        {
            if (flag)
            {
                sum_vw2 = valor_elemento*peso_elemento;
                texto_sum_vw2 = String.valueOf(valor_elemento) + "*" + String.valueOf(peso_elemento);
            }
            
            sum_trans2 = transicion;
            texto_sum_trans2 = String.valueOf(transicion);
        }
        else
        {
            if (flag)
            {
                sum_vw2 += valor_elemento*peso_elemento;
                texto_sum_vw2 += " + " + String.valueOf(valor_elemento) + "*" + String.valueOf(peso_elemento);
            }
            
            sum_trans2 += transicion;
            texto_sum_trans2 += " + " + String.valueOf(transicion);
        }
        d2 = sum_vw2 + sum_trans2;
        jTextField4.setText(String.valueOf(d2));
        
        texto_d2 = "(" + texto_sum_vw2 + ") + (" + texto_sum_trans2 + ")"; 
        jTextField5.setText(texto_d2);
    }
    
    public void calcular_d3()
    {
        if (texto_d3.equals(""))
        {
            if (flag)
            {
                sum_vw3 = valor_elemento*peso_elemento;
                texto_sum_vw3 = String.valueOf(valor_elemento) + "*" + String.valueOf(peso_elemento);
            }
            
            sum_trans3 = transicion;
            texto_sum_trans3 = String.valueOf(transicion);
        }
        else
        {
            if (flag)
            {
                sum_vw3 += valor_elemento*peso_elemento;
                texto_sum_vw3 += " + " + String.valueOf(valor_elemento) + "*" + String.valueOf(peso_elemento);
            }
            
            sum_trans3 += transicion;
            texto_sum_trans3 += " + " + String.valueOf(transicion);
        }
        d3 = sum_vw3 + sum_trans3;
        jTextField6.setText(String.valueOf(d3));
        
        texto_d3 = "(" + texto_sum_vw3 + ") + (" + texto_sum_trans3 + ")"; 
        jTextField7.setText(texto_d3);
    }
    
    public void calcular_D1()
    {
        D1 = d1 / r1;
        System.out.println("D1: " + String.valueOf(D1));
        //D1 = Math.toRadians(Math.atan(D1));
        D1 = Math.atan(D1);
        System.out.println("D1: " + String.valueOf(D1));
        D1 = D1 /(Math.PI/2);
        System.out.println("D1: " + String.valueOf(D1));
        D1 = D1 * MAX1;
        System.out.println("D1: " + String.valueOf(D1));
        jTextField8.setText(String.valueOf(D1));
        
        texto_D1 = "((tan-1";
        texto_D1 += "(" + String.valueOf(d1) + "/" + String.valueOf(r1) + "))";
        texto_D1 += "/(PI/2))*10";
        jTextField9.setText(texto_D1);
    }
    
    public void calcular_D2()
    {
        D2 = d2 / r2;
        System.out.println("D2: " + String.valueOf(D2));
        //D2 = Math.toRadians(Math.atan(D2));
        D2 = Math.atan(D2);
        System.out.println("D2: " + String.valueOf(D2));
        D2 = D2 /(Math.PI/2);
        System.out.println("D2: " + String.valueOf(D2));
        D2 = D2 * MAX2;
        System.out.println("D2: " + String.valueOf(D2));
        jTextField11.setText(String.valueOf(D2));
        
        texto_D2 = "((tan-1";
        texto_D2 += "(" + String.valueOf(d2) + "/" + String.valueOf(r2) + "))";
        texto_D2 += "/(PI/2))*30";
        jTextField10.setText(texto_D2);
    }
    
    public void calcular_D3()
    {
        D3 = d3 / r3;
        System.out.println("D3: " + String.valueOf(D3));
        //D3 = Math.toRadians(Math.atan(D3));
        D3 = Math.atan(D3);
        System.out.println("D3: " + String.valueOf(D3));
        D3 = D3 /(Math.PI/2);
        System.out.println("D3: " + String.valueOf(D3));
        D3 = D3 * MAX3;
        System.out.println("D3: " + String.valueOf(D3));
        jTextField13.setText(String.valueOf(D3));
        
        texto_D3 = "((tan-1";
        texto_D3 += "(" + String.valueOf(d3) + "/" + String.valueOf(r3) + "))";
        texto_D3 += "/(PI/2))*60";
        jTextField12.setText(texto_D3);
    }
    
    public void calcular_DT()
    {
        DT = D1 + D2 + D3;
        jTextField15.setText(String.valueOf(DT));
        jTextField14.setText(String.valueOf(D1) + " + " +
                String.valueOf(D2) + " + " +
                String.valueOf(D3));
        System.out.println("-------------------------------------------------------");
    }
    
    public void Transicion(int elemento_actual)
    {
        switch (elemento_anterior)
        {
            case 0://no hay elemento anterior
                transicion = racion*0;
                break;
            case 1://ARABE
                switch (elemento_actual)
                {
                    case 1://ARABE
                        transicion = racion*1;
                        break;
                    case 2://FLICK
                        transicion = racion*2;
                        break;
                    case 3://MORTAL
                        transicion = racion*6;
                        break;
                    case 4://WHIP
                        transicion = racion*5;
                        break;
                    case 5://LAYOUT
                        break;
                    case 6://GIRO
                        transicion = racion*17;
                        break;
                    case 7://2GIRO
                        break;
                }
                break;
            case 2://FLICK
                switch (elemento_actual)
                {
                    case 1://ARABE
                        break;
                    case 2://FLICK
                        transicion = racion*3;
                        break;
                    case 3://MORTAL
                        transicion = racion*11;
                        break;
                    case 4://WHIP
                        transicion = racion*4;
                        break;
                    case 5://LAYOUT
                        break;
                    case 6://GIRO
                        transicion = racion*14;
                        break;
                    case 7://2GIRO
                        transicion = racion*22;
                        break;
                }
                break;
            case 3://MORTAL
                switch (elemento_actual)
                {
                    case 1://ARABE
                        break;
                    case 2://FLICK
                        transicion = racion*7;
                        break;
                    case 3://MORTAL
                        transicion = racion*13;
                        break;
                    case 4://WHIP
                        transicion = racion*8;
                        break;
                    case 5://LAYOUT
                        break;
                    case 6://GIRO
                        transicion = racion*16;
                        break;
                    case 7://2GIRO
                        break;
                }
                break;
            case 4://WHIP
                switch (elemento_actual)
                {
                    case 1://ARABE
                        break;
                    case 2://FLICK
                        transicion = racion*9;
                        break;
                    case 3://MORTAL
                        transicion = racion*12;
                        break;
                    case 4://WHIP
                        transicion = racion*10;
                        break;
                    case 5://LAYOUT
                        break;
                    case 6://GIRO
                        transicion = racion*15;
                        break;
                    case 7://2GIRO
                        transicion = racion*23;
                        break;
                }
                break;
            case 5://LAYOUT
                switch (elemento_actual)
                {
                    case 1://ARABE
                        break;
                    case 2://FLICK
                        break;
                    case 3://MORTAL
                        break;
                    case 4://WHIP
                        break;
                    case 5://LAYOUT
                        break;
                    case 6://GIRO
                        break;
                    case 7://2GIRO
                        break;
                }
                break;
            case 6://GIRO
                switch (elemento_actual)
                {
                    case 1://ARABE
                        break;
                    case 2://FLICK
                        transicion = racion*18;
                        break;
                    case 3://MORTAL
                        transicion = racion*20;
                        break;
                    case 4://WHIP
                        transicion = racion*19;
                        break;
                    case 5://LAYOUT
                        break;
                    case 6://GIRO
                        transicion = racion*21;
                        break;
                    case 7://2GIRO
                        break;
                }
                break;
            case 7://2GIRO
                switch (elemento_actual)
                {
                    case 1://ARABE
                        break;
                    case 2://FLICK
                        transicion = racion*24;
                        break;
                    case 3://MORTAL
                        transicion = racion*26;
                        break;
                    case 4://WHIP
                        transicion = racion*25;
                        break;
                    case 5://LAYOUT
                        break;
                    case 6://GIRO
                        break;
                    case 7://2GIRO
                        break;
                }
                break;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
